/**
 * Created by MH on 8/3/2017.
 * Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

     Input:
     s = "abcd"
     t = "abcde"

     Output:
     e

     Explanation:
     'e' is the letter that was added.
 */
public class Find_the_Difference {
    public char findTheDifference(String s, String t) {
        char res = 0;
        for(int i = 0; i < t.length(); i++){
            res += t.charAt(i);
        }
        for(int i = 0; i < s.length(); i++){
            res -= s.charAt(i);
        }
        return res;
    }
}
